"use strict";
// Synthetic sources, real local SQL, stubbed providers. Never invokes production research or generation.
const test=require('node:test'),assert=require('node:assert/strict');
const {unzipSync,strFromU8}=require('fflate');
const C=require('../netlify/lib/grant-factory/core'),P=require('../netlify/lib/grant-factory/parser'),G=require('../netlify/lib/grant-factory/grant-reading'),Req=require('../netlify/lib/grant-factory/requirements'),E=require('../netlify/lib/grant-factory/eligibility'),M=require('../netlify/lib/grant-factory/project-model'),Review=require('../netlify/lib/grant-factory/proposal-review'),Assets=require('../netlify/lib/grant-factory/attachment-review');
const {exportPackage}=require('../netlify/lib/grant-factory/export'),{service}=require('../netlify/lib/grant-factory/service');
const {createTestRepo,ORG,OTHER}=require('./helpers/grant-db'),{project,confirmation}=require('./helpers/grant-proposal');
const doc=()=>({id:C.randomUUID(),org_id:ORG,title:'Synthetic full application',status:'AVAILABLE',extraction_status:'COMPLETE',sha256:'synthetic-hash',blocks:[{locator:'Page 1',text:'1. Describe the measured results. Maximum 100 words.'}]});
const question=extra=>P.question({id:C.randomUUID(),question_text:'Describe the measured results.',question_type:'NARRATIVE',required:true,limit_type:'WORDS',limit_value:100,source_quote:'1. Describe the measured results. Maximum 100 words.',source_locator:'Page 1',...extra});
const fact=extra=>({id:C.randomUUID(),org_id:ORG,fact_key:'results',display_name:'Measured results',value:'We documented 16 completed portfolios among 20 participants in the 2025 cohort.',verification_status:'APPROVED',external_use_allowed:true,grant_use_allowed:true,sensitivity_level:'PUBLIC',source_reference:'Synthetic cohort report',source_locator:'Results',temporal_context:'HISTORICAL',...extra});
function ready(){const d=doc(),f=fact(),q=question(),b={revision:1,documents:[d],facts:[f],programs:[]};const a={id:C.randomUUID(),org_id:ORG,revision:1,content:{grant_program_name:'Synthetic grant',status:'NEEDS_REVIEW',source_document_id:d.id,application_cycle:'2026',primary_program_id:C.randomUUID(),request_amount:250,eligibility:[],funder_requirements:[],attachments:[],inputs:[],strategy:{approved:true},project_model:project(d)},questions:[q],answers:[{id:C.randomUUID(),question_id:q.id,draft_text:f.value,evidence_ids:[f.id],status:'APPROVED'}]};Req.review(a,b,G.read([d],a),confirmation,{user_id:'synthetic-owner'});a.answers[0].audit={status:'COMPLETE',coverage_complete:true,text_hash:C.hash(f.value),brain_revision:1,evidence_hash:C.hash([f]),requirements_signature:C.requirementsSignature(a,b),claims:[]};Review.confirm(a,b,{reviewed:true,note:'Whole synthetic proposal and costed scope reviewed.',criteria:[]},{user_id:'synthetic-owner'});return {a,b,d,f,q};}

test('source checklist includes labels without question marks, formats, limits, optional and conditional fields',()=>{
 const text='Organization name\nFormat: Short text\nRequested funding amount\nFormat: Integer\nProject timeline\nFormat: Date\nUse of funds\nFormat: Narrative\nCharacter limit: 1200\nChoose a stage:\nFormat: Single choice\nOptions: Pilot | Scaling\nSelect topics:\nFormat: Multi select\nOptions: Youth | Wellbeing\nOptional supporting document\nFormat: Attachment\nModel card (if your solution uses AI)\nFormat: Attachment\nDeadline: 2026-10-16T20:00:00-04:00\nReview criteria: Youth involvement and testing.';
 const r=P.basic([{locator:'Portal 1',source_document_id:'source',text}]);
 for(const label of ['Organization name','Requested funding amount','Project timeline','Use of funds','Choose a stage:','Select topics:','Optional supporting document','Model card'])assert.ok(r.questions.some(q=>q.question_text.startsWith(label)),label);
 assert.equal(r.questions.find(q=>q.question_text.startsWith('Requested')).question_type,'NUMBER');assert.equal(r.questions.find(q=>q.question_text.startsWith('Project timeline')).question_type,'DATE');assert.equal(r.questions.find(q=>q.question_text.startsWith('Use')).limit_value,1200);assert.equal(r.questions.find(q=>q.question_text.startsWith('Choose')).question_type,'SINGLE_SELECT');assert.deepEqual(r.questions.find(q=>q.question_text.startsWith('Select')).options,['Youth','Wellbeing']);assert.equal(r.questions.find(q=>q.question_text.startsWith('Optional')).required,false);assert.match(r.questions.find(q=>q.question_text.startsWith('Model')).conditional_trigger,/if your/);assert.ok(r.funder_requirements.some(r=>/Deadline/.test(r.text)));assert.ok(r.funder_requirements.some(r=>r.kind==='CRITERION'));
});
test('canonical form metadata is not mistaken for another question and single/multiple choices stay distinct',()=>{
 const I=require('../netlify/lib/grant-factory/application-import');const html='<form><label for="stage">Stage</label><select id="stage" required><option>Pilot</option><option>Scaling</option></select><label for="topic">Topics</label><select id="topic" multiple><option>Youth</option><option>Wellbeing</option></select><label for="story">Your approach</label><textarea id="story" maxlength="1000"></textarea></form>';
 const sheet=I.formQuestions(html).sheet,r=P.basic([{locator:'Portal',text:sheet}]);assert.equal(r.questions.length,3);assert.equal(r.questions[0].question_type,'SINGLE_SELECT');assert.equal(r.questions[0].required,true);assert.equal(r.questions[1].question_type,'MULTI_SELECT');assert.equal(r.questions[1].required,false);assert.equal(r.questions[2].limit_value,1000);
});
test('AI extraction cannot hide basic source labels or turn explicit nonnarrative formats into prose',()=>{const blocks=[{locator:'Portal',text:'1. Organization name\nFormat: Short text\n2. Requested amount\nFormat: Integer\n3. Use of funds\nCharacter limit: 1000'}],original=P.basic(blocks);const parsed=P.normalize({questions:[{...original.questions[1],question_type:'NARRATIVE'}]},blocks);assert.equal(parsed.questions.length,3);assert.equal(parsed.questions[0].question_type,'NUMBER');assert.ok(parsed.questions.some(q=>q.limit_value===1000));});
test('URL-only, partial worksheet and truncated sources do not establish semantic completeness',()=>{
 const {a,b}=ready();const d=doc();d.blocks=[{locator:'URL',text:'https://fund.example/application'}];const reading=G.read([d],a);assert.equal(reading.complete,true);assert.ok(Req.diagnostics(reading).issues.some(i=>i.code==='URL_ONLY'));assert.throws(()=>Req.review(a,b,reading,confirmation,{user_id:'owner'}),/Supply readable/);
 d.blocks[0].text='Narrative only worksheet: not all fields are reflected on this worksheet. 1. Your impact?';const partial=G.read([d],a);assert.ok(Req.diagnostics(partial).issues.some(i=>i.code==='PARTIAL_WORKSHEET'));assert.throws(()=>Req.review(a,b,partial,confirmation,{user_id:'owner'}),/Attach the full portal/);assert.ok(Req.diagnostics({...partial,complete:false}).issues.some(i=>i.code==='TEXT_INCOMPLETE'));
});
test('competing deadlines and stale cycles retain source traces and need a documented resolution',()=>{const {a,b}=ready();const d=doc();d.blocks=[{locator:'FAQ',text:'Deadline: 2026-10-16T20:00:00-04:00\nApplication cycle: 2026'},{locator:'Quiz',text:'Deadline: 2026-10-20T20:00:00-04:00\nApplication cycle: 2025'}];const r=G.read([d],a),di=Req.diagnostics(r);assert.ok(di.issues.some(i=>i.code==='SOURCE_CYCLE'));const conflict=di.issues.find(i=>i.code==='SOURCE_CONFLICT');assert.equal(conflict.conflicts[0].values[0].source_locator,'FAQ');assert.throws(()=>Req.review(a,b,r,{...confirmation,note:''},{user_id:'owner'}),/resolution/);});
test('legacy repair preserves question IDs, human edits and original history; archival is explicit',()=>{const {a,b}=ready(),old=a.questions[0].id;a.answers[0].draft_text='Saved human wording';a.answers[0].edited_by='human';const missing=question({question_text:'Old field',source_quote:'Old field'});a.questions.push(missing);a.answers.push({id:C.randomUUID(),question_id:missing.id,draft_text:'Keep this too'});const parsed={...P.basic([{locator:'Page 1',text:'1. Describe the measured results. Maximum 50 words.\n2. Requested amount\nFormat: Integer'}]),attachments:[],eligibility:[]};const r=G.read(b.documents,a);a.content.reconciliation_preview=Req.preview(a,parsed,r,b);assert.equal(a.answers[0].draft_text,'Saved human wording');assert.ok(a.content.reconciliation_preview.changes.some(x=>x.fields?.includes('limit_value')));Req.apply(a,b,{reviewed:true,actor:'owner'});assert.equal(a.questions[0].id,old);assert.equal(a.questions[0].limit_value,50);assert.equal(a.answers[0].edited_by,'human');assert.ok(a.questions.some(q=>q.id===missing.id));assert.equal(a.content.reconciliation_history[0].previous.answers[1].draft_text,'Keep this too');a.content.reconciliation_preview=Req.preview(a,parsed,r,b);Req.apply(a,b,{reviewed:true,actor:'owner',archive_question_ids:[missing.id]});assert.ok(!a.questions.some(q=>q.id===missing.id));assert.equal(a.content.reconciliation_history.at(-1).previous.answers[1].draft_text,'Keep this too');});
test('ambiguous legacy matching and changed sources stop replacement without altering answers',()=>{const {a,b}=ready();a.questions.push({...a.questions[0],id:C.randomUUID()});const p={questions:[question()],attachments:[],eligibility:[]};a.content.reconciliation_preview=Req.preview(a,p,G.read(b.documents,a),b);assert.ok(a.content.reconciliation_preview.conflicts.length);assert.throws(()=>Req.apply(a,b,{reviewed:true}),/ambiguous/);b.documents[0].sha256='changed';assert.throws(()=>Req.apply(a,b,{reviewed:true}),/changed/);assert.equal(a.answers.length,1);});

test('eligibility distinguishes actual failure, missing evidence, conflicting facts, projections and conditional applicability',()=>{const f=fact({fact_key:'tax_exempt',value:'yes'}),rule={id:'r',rule:'Must be tax exempt',fact_key:'tax_exempt',operator:'EXACT',expected_value:'yes'};assert.equal(E.evaluate([rule],[f])[0].status,'PASS');assert.equal(E.evaluate([rule],[{...f,value:'no'}])[0].status,'FAIL');assert.equal(E.evaluate([rule],[])[0].status,'UNRESOLVED');assert.equal(E.evaluate([rule],[f,{...f,id:'other'}])[0].status,'UNRESOLVED');assert.equal(E.evaluate([rule],[{...f,expiration_date:'2000-01-01'}])[0].status,'UNRESOLVED');assert.equal(E.evaluate([rule],[{...f,verification_status:'PROJECTED'}])[0].status,'UNRESOLVED');const c={...rule,condition:{fact_key:'uses_ai',expected_value:'yes'}};assert.equal(E.evaluate([c],[f])[0].applicability,'UNRESOLVED');assert.equal(E.evaluate([c],[f,fact({fact_key:'uses_ai',value:'no'})])[0].applicability,'NOT_APPLICABLE');});
test('eligibility date comparisons use current time and explicit source timezone; human review cannot override hard failures',()=>{const rule={rule:'Deadline',fact_key:'CURRENT_DATE',operator:'DATE_BEFORE',expected_value:'2026-10-16T20:00:00-04:00'};assert.equal(E.evaluate([rule],[],new Date('2026-10-16T23:59:00Z'))[0].status,'PASS');assert.equal(E.evaluate([rule],[],new Date('2026-10-17T00:01:00Z'))[0].status,'FAIL');assert.equal(E.evaluate([{...rule,expected_value:'2026-10-16'}],[])[0].status,'UNRESOLVED');const {b,f}=ready();const failed={...E.evaluate([{fact_key:'results',operator:'EXACT',expected_value:'different'}],[f])[0],review:{approved:true,outcome:'PASS',brain_revision:b.revision,evidence_ids:[f.id]}};failed.review.requirement_hash=E.signature(failed);assert.equal(E.resolved(failed,b),false);});
test('traceable human eligibility decisions expire with changed requirements or evidence',()=>{const {b,f}=ready();const rule={id:'r',rule:'Review actual capacity',operator:'REVIEW'},r={approved:true,outcome:'PASS',brain_revision:b.revision,evidence_ids:[f.id],note:'Synthetic actual capacity checked',requirement_hash:E.signature(rule)};rule.review=r;assert.equal(E.resolved(rule,b),true);assert.equal(E.resolved(rule,{...b,revision:2}),false);assert.equal(E.resolved({...rule,rule:'Changed requirement'},b),false);});

test('decimal budget arithmetic, allocation and funding gap are deterministic',()=>{const m=project(doc());assert.equal(M.cost({quantity:'3',unit_rate:'0.10',duration:'2',allocation_percent:'50'}),30n);const v=M.validate(m,{request_amount:250});assert.equal(v.passed,true,JSON.stringify(v.issues));assert.deepEqual(v.totals,{cost:250,request:250,confirmed_other:0,funding_gap:250,currency:'USD'});assert.throws(()=>M.cost({...m.budget_lines[0],allocation_percent:'101'}),/Allocation/);assert.throws(()=>M.normalize({...m,budget_lines:[{...m.budget_lines[0],unit_rate:'12.345'}]}),/decimal/);});
for(const [name,change,code] of [
 ['unknown costs',m=>m.budget_lines[0].unit_rate=null,'BUDGET_UNKNOWN'],['over-allocation',m=>m.budget_lines[0].confirmed_other='100','BUDGET_ALLOCATION'],['request mismatch',m=>m.budget_lines[0].requested='100','REQUEST_BUDGET'],['prohibited cost',m=>m.budget_lines[0].eligibility='PROHIBITED','COST_ELIGIBILITY'],['staff-hour mismatch',m=>m.activities[0].staff_hours='20','STAFF_HOURS'],['organization versus solution',m=>m.solution_current_unique=200,'PARTICIPANT_SCOPE'],['unique versus encounters',m=>{m.solution_current_unique=20;m.solution_current_encounters=10;},'PARTICIPANT_BASIS'],['planned reach',m=>{m.delivery_status='PLANNED';m.solution_current_unique=20;},'PLANNED_REACH'],['pre-opening delivery',m=>m.activities[0].phase='DELIVERY','PREOPENING_DELIVERY'],['unknown denominator',m=>m.outcomes[0].denominator=null,'EVALUATION_DEFINITION'],['invalid calendar date',m=>m.end_date='2027-02-30','PROJECT_DATES'],['award-range failure',m=>{m.funder.award_min='500';m.funder.currency='USD';m.funder.award_range_status='STATED';},'AWARD_RANGE'],['grant-term mismatch',m=>{m.funder.grant_start='2027-08-01';m.funder.grant_end='2028-03-31';m.funder.grant_period_status='STATED';},'GRANT_PERIOD']])test('project validation identifies '+name,()=>{const m=project(doc());change(m);assert.ok(M.validate(m,{request_amount:250}).issues.some(i=>i.code===code),code);});

test('denominator-backed descriptive outcomes are allowed while unsupported rates and causal claims remain blocked',()=>{const sentence='80% of 20 participants completed a portfolio in the 2025 cohort.',f=fact({value:sentence});assert.equal(Review.rateSupported(sentence,[f]),true);assert.equal(C.deterministicAudit(sentence,[f],{limit_type:'NONE'}).length,0);assert.equal(Review.rateSupported('90% of participants gained employment.',[f]),false);assert.ok(C.deterministicAudit('90% of participants gained employment.',[f],{limit_type:'NONE'}).length);assert.equal(Review.rateSupported('Because of our program, 80% of 20 participants completed a portfolio.',[{...f,value:'Because of our program, 80% of 20 participants completed a portfolio.'}]),false);});
test('whole proposal detects repetition, request/count/date/status contradictions across answers without invented rubric scores',()=>{const {a,b,q}=ready();a.answers[0].draft_text='We will serve 35 youth. We request $500. The grant-funded project starts on 2027-03-01.';const long='Our existing program documented portfolios across the defined cohort with verified local records and a carefully attributed follow-up report for participating young people.';const q2=question({question_text:'Describe capacity'});a.questions.push(q2);a.answers[0].draft_text+=' '+long;a.answers.push({id:'a2',question_id:q2.id,draft_text:long,evidence_ids:[b.facts[0].id]});let r=Review.analyze(a,b);for(const code of ['PARTICIPANT_CONTRADICTION','REQUEST_CONTRADICTION','DATE_CONTRADICTION','REPETITION'])assert.ok(r.issues.some(i=>i.code===code),code);assert.equal(r.rubric_status,'NO_SUPPLIED_RUBRIC_EDITORIAL_REVIEW_ONLY');assert.equal(r.score,undefined);a.content.project_model.delivery_status='PLANNED';a.answers[0].draft_text='The solution currently serves 20 youth.';assert.ok(Review.analyze(a,b).issues.some(i=>i.code==='STATUS_CONTRADICTION'));});
test('actual criteria require reviewed response mappings; no omitted criterion can hide behind readiness',()=>{const {a,b,q}=ready();a.content.funder_requirements=[{id:'criterion',kind:'CRITERION',text:'Review criteria: Explain meaningful youth design.',source_quote:'Review criteria: Explain meaningful youth design.',source_locator:'RFP p2'}];assert.throws(()=>Review.confirm(a,b,{reviewed:true,note:'checked',criteria:[]},{user_id:'owner'}),/criterion/);Review.confirm(a,b,{reviewed:true,note:'Meaningful youth role assessed from supported text',criteria:[{id:'criterion',status:'COVERED',note:'Youth design covered in the mapped answer',question_ids:[q.id]}]},{user_id:'owner'});assert.equal(Review.issues(a,b).length,0);a.answers[0].draft_text+=' Changed.';assert.ok(Review.issues(a,b).length);});
test('complete readiness is current and invalidates on model, source, answer or brain changes',()=>{const {a,b}=ready();assert.equal(C.qa(a,b).passed,true,JSON.stringify(C.qa(a,b).issues));for(const change of [x=>x.a.content.project_model.solution_projected_unique=21,x=>x.b.revision++,x=>x.b.documents[0].sha256='new',x=>x.a.answers[0].draft_text+=' Changed.']){const copy=structuredClone({a,b});change(copy);assert.equal(C.qa(copy.a,copy.b).passed,false);}});

test('attachment review validates permissions, condition applicability, freshness, links, duration and rendered pages',()=>{const {a,b}=ready();const file={...doc(),filename:'impact.pdf',storage_path:ORG+'/impact/impact.pdf',external_use_allowed:true,byte_size:1000};b.documents.push(file);const att={id:'att',title:'Impact slide',required:true,document_id:file.id,reviewed:true,max_pages:1,allowed_formats:['pdf'],max_bytes:2000};a.content.attachments=[att];const v={document_signature:Assets.documentSignature(file),external_link:null,requirements_signature:C.requirementsSignature(a,b),format_confirmed:true,external_use_confirmed:true,page_count:1};att.validation_review=v;assert.equal(Assets.issues(a,b).length,0);file.external_use_allowed=false;assert.ok(Assets.issues(a,b).some(i=>i.code==='ATTACHMENT_PERMISSION'));file.external_use_allowed=true;file.sha256='updated';assert.ok(Assets.issues(a,b).some(i=>i.code==='ATTACHMENT_VALIDATION'));file.sha256='synthetic-hash';v.page_count=2;assert.ok(Assets.issues(a,b).some(i=>i.code==='ATTACHMENT_PAGES'));att.conditional_trigger='if technology used';assert.ok(Assets.issues(a,b).some(i=>i.code==='ATTACHMENT_CONDITION'));});
test('video links remain human-validated and upload requirements cannot disappear in the text vault',()=>{const {a,b}=ready();a.content.attachments=[{id:'video',title:'One minute video and link',required:true,external_link:'https://media.example/video',link_required:true,upload_required:true,max_duration_seconds:60,reviewed:true}];const v=a.content.attachments[0];v.validation_review={document_signature:null,external_link:v.external_link,requirements_signature:C.requirementsSignature(a,b),format_confirmed:true,external_use_confirmed:true,accessibility_confirmed:false,duration_seconds:70};for(const code of ['ATTACHMENT_UPLOAD','ATTACHMENT_ACCESS','ATTACHMENT_DURATION'])assert.ok(Assets.issues(a,b).some(i=>i.code===code),code);});
test('funder-only ZIP excludes internal provenance and notes; internal export is explicit and protected',async()=>{const {a,b}=ready();a.content.internal_note='PRIVATE REVIEW ONLY';a.content.approval={brain_revision:b.revision,answer_hash:C.hash(a.answers)};const ctx={org_id:ORG,role:'OWNER'};const fund=await exportPackage(a,b,{},ctx,'zip'),files=unzipSync(fund.bytes);assert.deepEqual(Object.keys(files),['application.docx']);const xml=strFromU8(unzipSync(files['application.docx'])['word/document.xml']);assert.doesNotMatch(xml,/PRIVATE REVIEW ONLY|INTERNAL-REVIEW|HUMAN-APPROVED|DRAFT —/);const internal=unzipSync((await exportPackage(a,b,{},ctx,'internal_zip')).bytes);assert.match(strFromU8(internal['INTERNAL-REVIEW/evidence-and-review.json']),/PRIVATE REVIEW ONLY/);await assert.rejects(exportPackage(a,b,{}, {...ctx,role:'GRANT_MANAGER'},'internal_zip'),/Executive/);await assert.rejects(exportPackage(a,b,{}, {...ctx,org_id:OTHER},'zip'),/not found/);});
test('funder exports reject over-limit text, stale final approval, invalid layouts and foreign evidence',async()=>{const {a,b,q}=ready(),ctx={org_id:ORG,role:'OWNER'};a.content.approval={brain_revision:b.revision,answer_hash:C.hash(a.answers)};a.answers[0].draft_text='word '.repeat(101);await assert.rejects(exportPackage(a,b,{},ctx,'docx'),/limit/);a.answers[0].draft_text=b.facts[0].value;q.limit_type='PAGES';q.limit_value=1;await assert.rejects(exportPackage(a,b,{},ctx,'docx'),/layout/);q.limit_type='WORDS';q.limit_value=100;a.content.approval.brain_revision=0;await assert.rejects(exportPackage(a,b,{},ctx,'zip'),/current final approval/);b.facts[0].org_id=OTHER;await assert.rejects(exportPackage(a,b,{},ctx,'json'),/Unauthorized/);});

let fixture;test.before(async()=>fixture=await createTestRepo());test.after(async()=>fixture.pg.close());
test('real SQL source repairs preserve populated answers, original documents and event history',async()=>{const {repo,owner}=fixture;const svc=service(repo,{enabled:false,call:()=>assert.fail('No model allowed')});let a=await svc.handle(owner,{action:'new_application',text:'1. Describe the measured results. Maximum 100 words.\n2. Old question?',grant_program_name:'Synthetic repair'});const original=a.content.source_document_id;const id=a.questions[0].id;const act=async(action,body={})=>a=await svc.handle(owner,{action,application_id:a.id,revision:a.revision,...body});await act('save_answer',{question_id:id,text:'Saved manual answer',evidence_ids:[]});await act('attach_application',{text:'1. Describe the measured results. Maximum 50 words.\n2. Requested amount\nFormat: Integer'});assert.equal(a.answers[0].draft_text,'Saved manual answer');assert.ok(a.content.original_source_document_ids.includes(original));assert.ok(a.content.reconciliation_preview);await act('apply_reconciliation',{reviewed:true});assert.equal(a.questions[0].id,id);assert.equal(a.answers[0].draft_text,'Saved manual answer');assert.equal(a.questions[0].limit_value,50);const history=await svc.handle(owner,{action:'history',id:a.id,kind:'application'});assert.ok(history.length>=3);assert.ok(await repo.document(owner,original));});
test('reconciliation, project and exports remain organization-scoped with no paid calls',async()=>{const {repo,owner,outsider}=fixture;const svc=service(repo,{enabled:false,call:()=>assert.fail('No paid calls')});let a=await svc.handle(owner,{action:'new_application',text:'1. Your approach?',grant_program_name:'Synthetic boundary'});for(const action of ['preview_reconciliation','apply_reconciliation','save_project_model','review_proposal','export'])await assert.rejects(svc.handle(outsider,{action,application_id:a.id,revision:a.revision,format:'internal_zip'}),/not found/);a=await svc.handle(owner,{action:'preview_reconciliation',application_id:a.id,revision:a.revision});assert.ok(a.content.reconciliation_preview);const run=(await fixture.pg.query('select count(*)::integer n from gf_ai_runs')).rows[0].n;assert.equal(run,0);});


test('incomplete source processing is rejected; partially processed applicant facts remain visibly qualified',async()=>{const {a,b,d,f}=ready();const repo={document:async()=>({...d,extraction_status:'PARTIAL'})};b.documents[0].extraction_status='PARTIAL';await assert.rejects(G.load(repo,{},b,a),/unreadable/);b.documents[0].extraction_status='COMPLETE';f.source_document_id=d.id;d.external_use_allowed=true;d.fact_extraction={status:'IN_PROGRESS',next_batch:2,total_batches:95};assert.ok(Review.analyze(a,b).warnings.some(w=>w.code==='SOURCE_FACT_PROCESSING'));});
test('attachment requirement changes retain manual file links, expose new limits and preserve removed rules until archival',()=>{const {a,b}=ready();a.content.attachments=[{id:'att',title:'Impact slide',max_pages:2,document_id:'saved-file',reviewed:true},{id:'old',title:'Old required file',required:true}];const parsed={questions:a.questions.map(q=>({...q,id:C.randomUUID()})),eligibility:[],funder_requirements:[],attachments:[{id:'new',title:'Impact slide',max_pages:1,source_quote:'Impact slide',source_locator:'Portal'}]};a.content.reconciliation_preview=Req.preview(a,parsed,G.read(b.documents,a),b);assert.ok(a.content.reconciliation_preview.requirement_changes.some(c=>c.id==='att'&&c.fields.includes('max_pages')));Req.apply(a,b,{reviewed:true});assert.equal(a.content.attachments[0].document_id,'saved-file');assert.equal(a.content.attachments[0].max_pages,1);assert.equal(a.content.attachments[0].reviewed,false);assert.ok(a.content.attachments.some(x=>x.id==='old'));assert.throws(()=>Req.review(a,b,G.read(b.documents,a),confirmation,{user_id:'owner'}),/retained/);});
test('conditional fields need a current source-based applicability decision and choice types are enforced',()=>{const {a,b,q}=ready();q.conditional_trigger='If technology is used';assert.ok(C.qa(a,b).issues.some(i=>i.code==='FIELD_CONDITION'));q.condition_review={applies:false,reason:'Reviewed original: no applicable technology solution',requirements_signature:C.requirementsSignature(a,b)};assert.ok(!C.qa(a,b).issues.some(i=>i.code==='FIELD_CONDITION'));q.conditional_trigger=null;q.question_type='SINGLE_SELECT';q.options=['Pilot','Scaling'];a.answers[0].draft_text='Unsupported option';assert.ok(C.qa(a,b).issues.some(i=>i.code==='FIELD_CHOICE'));q.question_type='MULTI_SELECT';a.answers[0].draft_text='Pilot\nScaling';assert.ok(!C.qa(a,b).issues.some(i=>i.code==='FIELD_CHOICE'));});
test('source-stated timing conflicts and expiry remain unresolved rather than silently using one value',()=>{const m=project(doc());m.funder.deadline_status='STATED';m.funder.deadline='2026-10-16T20:00:00-04:00';assert.ok(M.validate(m,{request_amount:250,deadline:'2026-10-20T20:00:00-04:00'},new Date('2026-10-10')).issues.some(i=>i.code==='FUNDER_VALUE_CONFLICT'));assert.ok(M.validate(m,{request_amount:250},new Date('2026-10-17T00:01Z')).issues.some(i=>i.code==='DEADLINE_PASSED'));m.funder.deadline='2026-10-16';assert.ok(M.validate(m,{request_amount:250}).issues.some(i=>i.code==='DEADLINE_TIMEZONE'));});
test('research and historical evidence cannot silently become current organizational outcomes',()=>{const {a,b,f}=ready();a.answers[0].draft_text='Our participants achieved improved grades.';f.research={record_id:'SYNTHETIC',external_use_status:'VERIFIED'};assert.ok(Review.analyze(a,b).issues.some(i=>i.code==='EVIDENCE_APPLICABILITY'));delete f.research;a.answers[0].draft_text='We currently serve 20 youth.';assert.ok(Review.analyze(a,b).issues.some(i=>i.code==='EVIDENCE_PERIOD'));});
test('real service rejects hard failure overrides, records source corrections, and invalidates old reviews',async()=>{const {repo,owner}=fixture;const svc=service(repo,{enabled:false});let a=await svc.handle(owner,{action:'new_application',text:'1. Your approach?\nApplicants must not have restricted status.',grant_program_name:'Synthetic eligibility correction'});let b=await repo.brain(owner);const f=fact({fact_key:'restricted_status',value:'no'});await repo.writeBrain(owner,b,[{table:'gf_facts',id:f.id,content:f}]);b=await repo.brain(owner);const rid=C.randomUUID();const base={id:rid,rule:'Applicants must not have restricted status.',operator:'EXACT',fact_key:'restricted_status',expected_value:'yes',source_locator:'Line 2',source_quote:'Applicants must not have restricted status.'};const act=async(action,body={})=>a=await svc.handle(owner,{action,application_id:a.id,revision:a.revision,...body});await act('save_eligibility',{eligibility:[base]});assert.equal(a.content.eligibility[0].status,'FAIL');await assert.rejects(act('review_eligibility',{rule_id:rid,outcome:'PASS',note:'Do not override hard failure',evidence_ids:[f.id]}),/hard eligibility failure/);await assert.rejects(act('save_eligibility',{eligibility:[{...base,expected_value:'no'}]}),/Explain the correction/);await act('save_eligibility',{eligibility:[{...base,expected_value:'no',correction_note:'Synthetic source/evidence transcription correction explicitly reviewed by owner'}]});assert.equal(a.content.eligibility[0].status,'PASS');assert.equal(a.content.parser_reviewed,false);});
test('project changes invalidate application, answer audits, strategy and whole-proposal review while preserving text',async()=>{const {repo,owner}=fixture;const svc=service(repo,{enabled:false});let a=await svc.handle(owner,{action:'new_application',text:'1. Your approach?',grant_program_name:'Synthetic model revisions'});a=await svc.handle(owner,{action:'save_answer',application_id:a.id,revision:a.revision,question_id:a.questions[0].id,text:'Saved manual narrative',evidence_ids:[]});a.content.strategy={approved:true};a.content.approval={by:'owner'};a.content.proposal_review={reviewed:true};a.answers[0].audit={status:'COMPLETE'};a=await repo.save(owner,a,await repo.brain(owner),'SYNTHETIC_REVIEW_STATE');const model=project(await repo.document(owner,a.content.source_document_id));a=await svc.handle(owner,{action:'save_project_model',application_id:a.id,revision:a.revision,project_model:model});assert.equal(a.answers[0].draft_text,'Saved manual narrative');assert.equal(a.answers[0].audit,null);assert.equal(a.content.approval,null);assert.equal(a.content.strategy.approved,false);assert.equal(a.content.proposal_review,null);});

test('current human eligibility failure or unresolved decision blocks a deterministic pass, and hard failures remain immutable',()=>{const {a,b,f}=ready();const raw={id:'review-rule',rule:'Approved status required',fact_key:f.fact_key,operator:'EXACT',expected_value:f.value};let rule=E.evaluate([raw],[f])[0];assert.equal(rule.status,'PASS');rule.review={approved:false,outcome:'FAIL',note:'Additional source requirement not established',requirement_hash:E.signature(rule),brain_revision:b.revision,evidence_ids:[f.id]};assert.equal(E.effective(rule,b,a.id).status,'FAIL');assert.equal(E.resolved(rule,b,a.id),false);rule.review.outcome='UNRESOLVED';assert.equal(E.resolved(rule,b,a.id),false);b.revision++;assert.equal(E.resolved(rule,b,a.id),true);rule=E.evaluate([{...raw,expected_value:'different'}],[f])[0];rule.review={approved:true,outcome:'PASS',note:'Cannot override',requirement_hash:E.signature(rule),brain_revision:b.revision,evidence_ids:[f.id]};assert.equal(E.effective(rule,b,a.id).status,'FAIL');assert.equal(E.resolved(rule,b,a.id),false);});

test('unapplied material source repairs block final readiness, while an unchanged comparison remains current',()=>{const {a,b}=ready();assert.equal(Req.issues(a,b).length,0);a.content.reconciliation_preview={changes:[{kind:'UNCHANGED'}],requirement_changes:[],conflicts:[]};assert.equal(Req.issues(a,b).length,0);a.content.reconciliation_preview.changes.push({kind:'ADDED'});assert.ok(C.qa(a,b).issues.some(i=>i.code==='REQUIREMENTS_REPAIR_PENDING'));});

test('eligibility deadline comparisons require an explicit time zone, not just a date/time separator',()=>{const rule={operator:'DATE_BEFORE',fact_key:'CURRENT_DATE',expected_value:'2026-10-16T17:00:00',rule:'Submit by the deadline'};assert.equal(E.evaluate([rule],[],new Date('2026-10-10T00:00:00Z'))[0].status,'UNRESOLVED');rule.expected_value+='-04:00';assert.equal(E.evaluate([rule],[],new Date('2026-10-10T00:00:00Z'))[0].status,'PASS');});
