"use strict";
const VERSION='PROPOSAL_REVIEW_2026-10-10';
function rateSupported(sentence,evidence){const rates=sentence.match(/\d+(?:\.\d+)?\s*%/g)||[];if(!rates.length)return false;
 return rates.every(rate=>evidence.some(f=>{if(f.temporal_context==='PLANNED'||f.verification_status==='PROJECTED')return false;const value=String(f.value);const denom=f.metric?.denominator;const numerator=f.metric?.numerator;const exact=value.toLowerCase().replace(/\s+/g,' ').includes(sentence.trim().toLowerCase().replace(/\s+/g,' '));
 const hasDenominator=/\b(?:of|among|cohort of|out of)\s+\d[\d,]*\s+(?:participants|graduates|alumni|students|respondents|youth|people)/i.test(value);
 const validMetric=Number.isFinite(Number(denom))&&Number(denom)>0&&Number.isFinite(Number(numerator))&&Number(numerator)>=0&&Number(numerator)<=Number(denom)&&Math.abs(100*Number(numerator)/Number(denom)-parseFloat(rate))<0.11;
 return exact&&value.includes(rate)&&(hasDenominator||validMetric)&&(!/\b(?:caused|because of our|as a result of our|solely due to)\b/i.test(sentence)||f.causal_evidence===true);
 }));
}
function criteria(app){const C=require('./core');const raw=(app.content.funder_requirements||[]).filter(r=>r.kind==='CRITERION'||/review criter|rubric|evaluat.*proposal|selection criter|applications? (?:will be|are) (?:assessed|judged|reviewed)/i.test(r.text||''));
 if(app.content.rubric_or_scoring)raw.push({text:app.content.rubric_or_scoring,source_locator:'Application rubric — compare with original',source_document_id:app.content.source_document_id,source_quote:app.content.rubric_or_scoring});
 const unique=new Map();for(const r of raw)unique.set(r.text,{...r,id:r.id||C.hash([r.text,r.source_locator]).slice(0,24)});return [...unique.values()];
}
function signature(app,brain){const C=require('./core');return C.hash({requirements:C.requirementsSignature(app,brain),answers:app.answers.map(a=>[a.id,a.question_id,a.draft_text,a.evidence_ids,a.status]),project:app.content.project_model,brain_revision:brain.revision});}
function analyze(app,brain){const C=require('./core'),M=require('./project-model');const issues=[],warnings=[];const add=(code,message,question_ids=[])=>issues.push({code,message,question_ids});const model=app.content.project_model;
 const valid=new Set(C.authorizedFacts(brain,app.id).map(f=>f.id));const sentenceOwners=new Map();
 for(const a of app.answers){const q=app.questions.find(q=>q.id===a.question_id);if(!q)continue;const ev=(a.evidence_ids||[]).map(id=>brain.facts.find(f=>f.id===id&&valid.has(id))).filter(Boolean);
  for(const f of ev){const d=brain.documents.find(d=>d.id===f.source_document_id);if(d?.fact_extraction&&d.fact_extraction.status!=='COMPLETE')warnings.push({code:'SOURCE_FACT_PROCESSING',message:'A cited document has only some sections processed. Individually approved facts can be used, but review unprocessed sections for missing context.',document_id:d.id});}
  for(const finding of C.deterministicAudit(a.draft_text||'',ev,q))if(['UNSUPPORTED','OVERSTATED','CONFLICTED'].includes(finding.status))add('CLAIM',finding.reason,[q.id]);
  for(const s of String(a.draft_text||'').split(/(?<=[.!?])\s+|\n+/)){
   const n=s.trim().toLowerCase().replace(/\s+/g,' ');if(n.split(' ').length>=18){if(sentenceOwners.has(n))add('REPETITION','A substantial sentence is repeated. Check whether each answer advances the case.',[sentenceOwners.get(n),q.id]);else sentenceOwners.set(n,q.id);}
   if(ev.some(f=>f.research)&&/\b(?:our|this solution's) (?:participants|students|youth).{0,70}(?:achieved|gained|improved|completed)/i.test(s)&&!ev.some(f=>!f.research&&String(f.value).includes(s)))add('EVIDENCE_APPLICABILITY','External research cannot establish this organization or solution’s achieved results.',[q.id]);
   if(ev.some(f=>f.temporal_context==='HISTORICAL')&&/\b(?:currently|now|this year)\b/i.test(s)&&!ev.some(f=>f.temporal_context==='CURRENT'&&String(f.value).includes(s)))add('EVIDENCE_PERIOD','Historical evidence does not establish the current-period claim.',[q.id]);
   if(model){for(const [re,key,label]of [[/\b(?:will|plan to|projected to) serve\s+([\d,]+)\s+(?:unique\s+)?(?:students|participants|youth|people)\b/i,'solution_projected_unique','projected solution reach'],[/\b(?:currently|now) serv(?:e|es|ing)\s+([\d,]+)\s+(?:unique\s+)?(?:students|participants|youth|people)\b/i,'solution_current_unique','current solution reach']]){const m=s.match(re);if(m&&model[key]!=null&&Number(m[1].replace(/,/g,''))!==model[key])add('PARTICIPANT_CONTRADICTION','Answer conflicts with the shared '+label+'.',[q.id]);}
    if(model.delivery_status==='PLANNED'&&/\b(?:currently|now|already)\b/i.test(s)&&/\b(?:serves?|operates?|enrolls?)\b/i.test(s)&&!(/historical|related.program|previous|past|existing work/i.test(s)))add('STATUS_CONTRADICTION','A planned solution is described as currently delivered. Separate established work from the expansion.',[q.id]);
    const dates=[...s.matchAll(/\b\d{4}-\d{2}-\d{2}\b/g)].map(m=>m[0]);for(const d of dates)if(/(?:project|delivery|grant-funded).{0,45}(?:starts?|begins?|ends?|runs?)/i.test(s)&&M.date(d)!=null&&((M.date(model.start_date)!=null&&M.date(d)<M.date(model.start_date))||(M.date(model.end_date)!=null&&M.date(d)>M.date(model.end_date))))add('DATE_CONTRADICTION','A narrative project date falls outside the shared delivery period.',[q.id]);
    for(const m of s.matchAll(/\b(?:request(?:ing|ed)?(?:\s+amount)?(?:\s+of)?|seek(?:ing)?)\s*\$([\d,]+(?:\.\d+)?)/gi))if(app.content.request_amount==null||Number(m[1].replace(/,/g,''))!==Number(app.content.request_amount))add('REQUEST_CONTRADICTION','Narrative requested amount differs from the costed application request.',[q.id]);
   }
  }
 }
 const cs=criteria(app);return {version:VERSION,signature:signature(app,brain),issues,warnings,criteria:cs.map(r=>({...r,status:'UNRESOLVED',candidate_question_ids:app.questions.filter(q=>{const words=(r.text||'').toLowerCase().match(/[a-z]{5,}/g)||[];return words.some(w=>(q.question_text+' '+(app.answers.find(a=>a.question_id===q.id)?.draft_text||'')).toLowerCase().includes(w));}).map(q=>q.id)})),editorial_checklist:['Lead with the relevant proven result and fundable next step.','Connect need, activities, cost, capacity and evaluation.','Separate organizational history from solution results and planned expansion.','Attribute claims to their actual population, period, denominator and source.','Check the whole proposal for contradictions, repetition and omitted requirements.'],rubric_status:cs.length?'SUPPLIED_FUNDER_CRITERIA':'NO_SUPPLIED_RUBRIC_EDITORIAL_REVIEW_ONLY',note:'Candidate matches are reading aids, not semantic confirmation, scores, eligibility or odds of funding.'};}
function confirm(app,brain,body,ctx){const C=require('./core');const result=analyze(app,brain);if(!body.reviewed||!body.note?.trim())C.fail('Review the whole proposal and record the decision.');if(result.issues.length)C.fail('Resolve the whole-proposal findings before confirming review.',409);
 const reviews=body.criteria||[];for(const c of result.criteria){const r=reviews.find(r=>r.id===c.id);if(!r||r.status!=='COVERED'||!r.note?.trim()||!r.question_ids?.length||r.question_ids.some(id=>!app.questions.some(q=>q.id===id)||!app.answers.some(a=>a.question_id===id&&a.draft_text?.trim())))C.fail('Explain how each supplied funder criterion is answered; unresolved criteria block approval.');}
 app.content.proposal_review={...result,criteria:reviews,reviewed:true,by:ctx.user_id,at:C.now(),note:C.str(body.note,4000),signature:signature(app,brain)};
}
function issues(app,brain){const r=app.content.proposal_review;if(!r?.reviewed||r.signature!==signature(app,brain))return [{code:'PROPOSAL_REVIEW',message:'Review the complete proposal against actual funder criteria and the shared project model. Previous review is stale after material changes.'}];return analyze(app,brain).issues;}
function context(app,questionId){let remaining=24000;const answers=[];for(const a of app.answers.filter(a=>a.question_id!==questionId)){if(remaining<=0)break;const text=String(a.draft_text||'').slice(0,Math.min(5000,remaining));remaining-=text.length;answers.push({question_id:a.question_id,text});}return {status:'UNREVIEWED_CONTEXT_NOT_EVIDENCE',answers,excerpt_only:true,note:'Other answers guide coherence only; whole-proposal human review remains necessary.'};}
module.exports={context,VERSION,rateSupported,criteria,signature,analyze,confirm,issues};
